scope: ha_cluster
namespace: /service/

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  postgresql:
    use_pg_rewind: true

  initdb:
  - encoding: UTF8
  - data-checksums

  post_init: /patroni_post_init.sh


etcd3:
  hosts:
  - etcd1:2379
  - etcd2:2379
  - etcd3:2379

postgresql:
  authentication:
    replication:
      username: pgrepl
      password: pgrepl123
    super_user:
      username: postgres
      password: postgres123
  
  listen: 0.0.0.0:5432
  data_dir: /var/lib/postgresql/patroni/main
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /tmp/pgpass0
  
  parameters:
    unix_socket_directories: /var/run/postgresql
  
  pg_hba:
  - host replication all all trust
  - host all all all trust

watchdog:
  mode: off

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false